server:
  port: 9000
spring:
  application:
    name: "cards"
  datasource:
    url: "jdbc:mysql://localhost:3308/cardsdb"
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "qa"

  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka"

info:
  app:
    name: "cards"
    description: "Cards Microservice"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        cards: DEBUG