spring:
  application:
    name: "configserver"

  profiles:
#    active: native
    active: git

  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/AravindN-devops/eazybytes-config.git"
          default-label: main
          timeout: 50
          clone-on-start: true
          force-pull: true


server:
  port: 8071

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"