services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 40s
      timeout: 10s
      retries: 10
      start_period: 60s

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cardsdb
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 40s
      timeout: 10s
      retries: 10
      start_period: 60s

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 40s
      timeout: 10s
      retries: 10
      start_period: 60s

  configserver:
    image: aravindnimmala/configserver:s3
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:8071/actuator/health"]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      accountsdb:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      cardsdb:
        condition: service_healthy

  eurekaserver:
    image: aravindnimmala/eurekaserver:s3
    container_name: eurekaserver
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/actuator/health"]
      interval: 40s
      timeout: 10s
      start_period: 40s
      retries: 5

  gatewayserver:
    image: aravindnimmala/gatewayserver:s3
    container_name: gatewayserver
    ports:
      - "8072:8072"
    networks:
      - eazybank
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      accounts:
        condition: service_healthy
      accounts1:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8072/actuator/health"]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_APPLICATION_NAME: "gatewayserver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"


  accounts:
    image: aravindnimmala/accounts:s3
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_SQL_INIT_MODE: always
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s

  accounts1:
    image: aravindnimmala/accounts:s3
    container_name: accounts1
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8071/"
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_SQL_INIT_MODE: always
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s


  loans:
    image: aravindnimmala/loans:s3
    container_name: loans
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071"
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_SQL_INIT_MODE: always
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/actuator/health" ]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s

  cards:
    image: aravindnimmala/cards:s3
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071"
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_SQL_INIT_MODE: always
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      interval: 40s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  eazybank:
    driver: bridge
